CREATE TABLE users(
 id INT AUTO_INCREMENT PRIMARY KEY,
 email VARCHAR(255),
 password VARCHAR(255)
);
CREATE TABLE tasks(
 id INT AUTO_INCREMENT PRIMARY KEY,
 user_id INT,
 title VARCHAR(255),
 FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);